version: '2'

services:

  elasticsearch:
    image: elasticsearch:1.7.4
    container_name: elasticsearch

    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:4.1.5
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

    depends_on:
      - elasticsearch

    ports:
      - "5601:5601"

  neo4j:
    image: neo4j:2.3.2
    container_name: neo4j
    environment:
      NEO4J_AUTH: none

    volumes:
      - ./data/neo4j:/data

    ports:
      - "7474:7474"

  service:
    image: iotudresden/feedback-service
    container_name: feedback
    environment:
      SPRING_DATA_ELASTICSEARCH_CLUSTER-NODES: elasticsearch:9300
      METRICS_REPORTER_ELASTICSEARCH_NODES: elasticsearch:9200
      SERVICE_KNOWLEDGE_NEO4J_URL: http://neo4j:7474
      SERVER_PORT: 9000
      OPENHAB_HOST: ${OPENHAB_HOST}

    depends_on:
      - elasticsearch
      - neo4j

    ports:
      - "9000:9000"
