server.port: 9000

spring:
  main.showBanner: false
  data.rest:
    returnBodyOnCreate: true
    returnBodyOnUpdate: true

service:
  knowledge:
    neo4j:
      url: http://localhost:7474
      username:
      password:

    elasticsearch:
      host:
      port: 9300