server.port: 9000
management.port: 9001

spring:
  main.showBanner: false
  data.rest:
    returnBodyOnCreate: true
    returnBodyOnUpdate: true

service.knowledge:
  url: http://localhost:7474
  username:
  password: